"""Data models for the planning layer (M6 Build Phase B)."""
from __future__ import annotations

from datetime import datetime, timezone
from typing import Any
from uuid import uuid4

from pydantic import BaseModel, Field

from agentic.goal.models import RiskLevel


class ExecutionNode(BaseModel):
    """A single step in an execution plan."""
    id: str = Field(default_factory=lambda: str(uuid4()))
    goal_id: str
    action_type: str
    tool_name: str | None = None
    required_inputs: dict[str, Any] = Field(default_factory=dict)
    expected_outputs: dict[str, Any] = Field(default_factory=dict)
    estimated_duration: float = 0.0  # In hours
    estimated_cost: float = 0.0  # In USD
    estimated_tokens: int = 0
    risk_level: RiskLevel = RiskLevel.LOW
    approval_required: bool = False
    dependencies: list[str] = Field(default_factory=list)  # Node IDs this node depends on
    success_probability: float = 1.0  # 0.0 to 1.0
    business_value: float = 0.0  # Normalized 0.0 to 1.0
    rollback_strategy: str = ""


class ExecutionEdge(BaseModel):
    """A dependency link between two execution nodes."""
    from_node: str
    to_node: str
    dependency_type: str  # e.g., "sequential", "data_flow"


class ExecutionGraph(BaseModel):
    """The full DAG representing the plan steps and their order."""
    nodes: dict[str, ExecutionNode] = Field(default_factory=dict)
    edges: list[ExecutionEdge] = Field(default_factory=list)
    estimated_total_cost: float = 0.0
    estimated_duration: float = 0.0  # Total critical path duration
    estimated_roi: float = 0.0
    estimated_risk: float = 0.0


class HistoricalEvidence(BaseModel):
    """Historical telemetry supporting planning assertions."""
    related_action: str
    previous_outcomes: list[bool] = Field(default_factory=list)
    average_success: float = 0.0
    confidence: float = 0.0


class DecisionAlternative(BaseModel):
    """A candidate alternative plan formulated during optimization."""
    id: str = Field(default_factory=lambda: str(uuid4()))
    description: str
    pros: list[str] = Field(default_factory=list)
    cons: list[str] = Field(default_factory=list)
    estimated_roi: float = 0.0
    estimated_risk: float = 0.0
    confidence: float = 0.0
    graph: ExecutionGraph


class Plan(BaseModel):
    """A candidate execution plan generated by the Planner."""
    id: str = Field(default_factory=lambda: str(uuid4()))
    goal_id: str
    tenant_id: str
    site_id: str
    version: int = 1
    graph: ExecutionGraph
    alternatives: list[DecisionAlternative] = Field(default_factory=list)
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    is_active: bool = True
