"""Property 55 — Missing required secret fails startup naming the key, not the value.

Feature: website-orchestrator-milestone-0, Property 55: Missing required secret
fails startup naming the key, not the value

Validates: Requirements 14.2

Requirement 14.2: IF a required secret is not available from environment
variables or a ``.env`` file when the Website_Orchestrator starts, THEN THE
Website_Orchestrator SHALL fail to start and SHALL raise an error indicating
which required secret is missing WITHOUT exposing any secret value.

The single required secret in Milestone 0 is ``WP_APPLICATION_PASSWORD`` (held as
a :class:`pydantic.SecretStr`). This property drives :func:`core.config.load_settings`
with the secret genuinely absent (process env cleared, ``.env`` disabled via
``_env_file=None``) while the four required non-secret settings are supplied, and
asserts that:

* startup fails with :class:`core.exceptions.MissingSecretError`;
* the error NAMES the missing key (``WP_APPLICATION_PASSWORD``); and
* a freely generated candidate secret value NEVER appears anywhere in the
  error's string form or its attributes.

The candidate secret value is generated by Hypothesis but deliberately *not*
injected into the environment or the overrides — it stands in for "whatever the
operator's real secret might have been". Because the value is never handed to the
loader, it can only surface in the error through an accidental leak, which is
exactly what this property forbids.
"""

from __future__ import annotations

import os
from unittest import mock

import pytest
from hypothesis import assume, given
from hypothesis import strategies as st

from core.config import load_settings
from core.exceptions import MissingSecretError

# The environment variables the loader reads. Cleared for every example so the
# real developer environment / ``.env`` can never satisfy the required secret.
_ENV_KEYS = (
    "DATABASE_URL",
    "TENANT_ID",
    "WP_BASE_URL",
    "WP_USERNAME",
    "WP_APPLICATION_PASSWORD",
)

# The four required, non-secret settings. Supplied via overrides so the ONLY
# missing required field is the secret ``WP_APPLICATION_PASSWORD``.
_NON_SECRET_OVERRIDES = {
    "database_url": "postgresql://user@localhost:5432/wo",
    "tenant_id": "tenant-under-test",
    "wp_base_url": "https://example.test",
    "wp_username": "editor",
}

_MISSING_KEY = "WP_APPLICATION_PASSWORD"


def _error_surface(exc: MissingSecretError) -> str:
    """Concatenate every place the exception could plausibly leak text.

    Covers the human-readable message, the ``repr``, the raw ``args`` tuple, and
    the public ``key``/``keys`` attributes so the "no secret value" assertion is
    total.
    """
    return " || ".join(
        [
            str(exc),
            repr(exc),
            repr(exc.args),
            repr(getattr(exc, "key", None)),
            repr(getattr(exc, "keys", None)),
        ]
    )


@given(
    # A broad family of candidate secret values: printable text of non-trivial
    # length. This exercises a large slice of the secret input space while
    # avoiding degenerate single-character strings that would coincidentally be
    # substrings of the generic, value-free error message.
    secret_value=st.text(
        alphabet=st.characters(min_codepoint=0x20, max_codepoint=0x7E),
        min_size=4,
        max_size=64,
    )
)
def test_missing_secret_names_key_never_value(secret_value: str) -> None:
    """For any candidate secret value, a genuinely-absent secret fails startup
    with ``MissingSecretError`` that names the key but never the value."""
    # ``clear=True`` removes the entire process environment for the duration of
    # the call (and restores it afterwards), and ``_env_file=None`` disables the
    # ``.env`` source. Together they guarantee ``WP_APPLICATION_PASSWORD`` is
    # genuinely unavailable — nothing on the developer's machine can satisfy it.
    with mock.patch.dict(os.environ, {}, clear=True):
        with pytest.raises(MissingSecretError) as exc_info:
            load_settings(_env_file=None, **_NON_SECRET_OVERRIDES)

    surface = _error_surface(exc_info.value)

    # The error must NAME the missing key so operators can fix their config.
    assert _MISSING_KEY in surface

    # Skip the (leak-free) coincidence where the generated value is itself a
    # substring of the FIXED, value-free error text: that is not the secret
    # leaking, it is the fixed diagnostic wording. That fixed text is more than
    # just the message — it also includes the class name in ``repr`` (e.g.
    # "MissingSecretError"), the key name, and the ``keys`` list repr. Comparing
    # against the surface of a reference error built from the KEY ALONE (no
    # secret value ever passes through it) covers every one of those sources, so
    # a short generated value like "ingS" (a substring of "MissingSecretError")
    # is correctly treated as noise rather than a leak.
    reference_surface = _error_surface(MissingSecretError(_MISSING_KEY))
    assume(secret_value not in reference_surface)

    # The candidate secret VALUE must never appear anywhere in the error.
    assert secret_value not in surface


def test_missing_secret_does_not_leak_specific_value() -> None:
    """Unit example: a concrete, obviously-secret value never leaks and the key
    is named. Complements the property with a deterministic, readable case."""
    obvious_secret = "hunter2-SUPER-SECRET-do-not-leak-xyz789"
    with mock.patch.dict(os.environ, {}, clear=True):
        with pytest.raises(MissingSecretError) as exc_info:
            load_settings(_env_file=None, **_NON_SECRET_OVERRIDES)

    surface = _error_surface(exc_info.value)
    assert _MISSING_KEY in surface
    assert obvious_secret not in surface


def test_present_secret_does_not_raise() -> None:
    """Sanity check: when the secret IS supplied, startup succeeds — so the
    property's failure is caused specifically by the absent secret, not by the
    other overrides."""
    with mock.patch.dict(os.environ, {}, clear=True):
        settings = load_settings(
            _env_file=None,
            wp_application_password="present-secret",
            **_NON_SECRET_OVERRIDES,
        )
    # SecretStr keeps the value out of its string form.
    assert "present-secret" not in str(settings)


# ---------------------------------------------------------------------------
# Extended Property 55: message formatting never contains brackets or quotes
# ---------------------------------------------------------------------------


@given(
    missing_keys=st.lists(
        st.from_regex(r"[A-Z][A-Z0-9_]{2,30}", fullmatch=True),
        min_size=1,
        max_size=5,
        unique=True,
    )
)
def test_missing_secret_message_never_contains_brackets_or_quotes(
    missing_keys: list[str],
) -> None:
    """For any generated set of missing keys, the rendered error message never
    contains ``[``, ``]``, or ``'`` — preventing raw Python list repr from
    leaking into user-facing output."""
    exc = MissingSecretError(missing_keys)
    message = str(exc)
    assert "[" not in message, f"Message contains '[': {message!r}"
    assert "]" not in message, f"Message contains ']': {message!r}"
    assert "'" not in message, f"Message contains quote: {message!r}"

    # Also verify each key is present in the message
    for key in missing_keys:
        assert key in message, f"Key {key!r} not found in message: {message!r}"


# ---------------------------------------------------------------------------
# Unit tests: single vs multiple missing keys
# ---------------------------------------------------------------------------


def test_missing_secret_error_single_key_message() -> None:
    """Single missing key -> singular 'secret' label, key on its own line."""
    exc = MissingSecretError("WP_APPLICATION_PASSWORD")
    message = str(exc)
    assert message == "Missing required secret:\nWP_APPLICATION_PASSWORD"
    assert exc.key == "WP_APPLICATION_PASSWORD"
    assert exc.keys == ["WP_APPLICATION_PASSWORD"]


def test_missing_secret_error_multiple_keys_message() -> None:
    """Multiple missing keys -> plural 'secrets' label, one key per line, no
    brackets or quote characters anywhere in the message."""
    exc = MissingSecretError(["WP_APPLICATION_PASSWORD", "WP_USERNAME"])
    message = str(exc)
    assert message == (
        "Missing required secrets:\nWP_APPLICATION_PASSWORD\nWP_USERNAME"
    )
    assert "[" not in message
    assert "]" not in message
    assert "'" not in message
    assert exc.keys == ["WP_APPLICATION_PASSWORD", "WP_USERNAME"]
    assert exc.key == "WP_APPLICATION_PASSWORD, WP_USERNAME"
