"""initial Digital_Twin schema

Creates the six relational tables of the Digital_Twin (Req 3.1) — pages, links,
page_metadata, issues, suggested_fixes, audit_trail — each with a non-null
``tenant_id`` column (Req 14.4). Storage is relational only; no graph database
and no embeddings (Req 3.7).

This migration is hand-authored to match digital_twin.models exactly. It was not
autogenerated because the local environment had no reachable PostgreSQL/psycopg
driver at authoring time; the column set is kept in lockstep with the ORM models
and verified via metadata construction and create_all.

Revision ID: 0001_initial
Revises:
Create Date: 2024-01-01 00:00:00

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "pages",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("final_url", sa.String(), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column("has_schema", sa.Boolean(), nullable=False),
        sa.Column("crawled_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_pages_tenant_id", "pages", ["tenant_id"])
    op.create_index("ix_pages_tenant_url", "pages", ["tenant_id", "url"])

    op.create_table(
        "links",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column("page_id", sa.String(), nullable=False),
        sa.Column("href", sa.String(), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("reachable", sa.Boolean(), nullable=False),
        sa.Column("redirect_chain_len", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["page_id"], ["pages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_links_tenant_id", "links", ["tenant_id"])
    op.create_index("ix_links_page_id", "links", ["page_id"])

    op.create_table(
        "page_metadata",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column("page_id", sa.String(), nullable=False),
        sa.Column("meta_description", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["page_id"], ["pages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_page_metadata_tenant_id", "page_metadata", ["tenant_id"])
    op.create_index("ix_page_metadata_page_id", "page_metadata", ["page_id"])

    op.create_table(
        "issues",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column("page_id", sa.String(), nullable=False),
        sa.Column("issue_type", sa.String(), nullable=False),
        sa.Column("severity", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("ignored", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["page_id"], ["pages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_issues_tenant_id", "issues", ["tenant_id"])
    op.create_index("ix_issues_page_id", "issues", ["page_id"])

    op.create_table(
        "suggested_fixes",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column("issue_id", sa.String(), nullable=False),
        sa.Column("fix_type", sa.String(), nullable=True),
        sa.Column("auto_applicable", sa.Integer(), nullable=False),
        sa.Column("target_media_id", sa.Integer(), nullable=True),
        sa.Column("target_page_id", sa.Integer(), nullable=True),
        sa.Column("proposed_value", sa.Text(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["issue_id"], ["issues.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_suggested_fixes_tenant_id", "suggested_fixes", ["tenant_id"])
    op.create_index("ix_suggested_fixes_issue_id", "suggested_fixes", ["issue_id"])

    op.create_table(
        "audit_trail",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column("fix_id", sa.String(), nullable=False),
        sa.Column("actor", sa.String(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("transition", sa.String(), nullable=False),
        sa.Column("before_value", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["fix_id"], ["suggested_fixes.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_audit_trail_tenant_id", "audit_trail", ["tenant_id"])
    op.create_index("ix_audit_trail_fix_id", "audit_trail", ["fix_id"])
    op.create_index(
        "ix_audit_trail_tenant_created", "audit_trail", ["tenant_id", "created_at"]
    )


def downgrade() -> None:
    op.drop_index("ix_audit_trail_tenant_created", table_name="audit_trail")
    op.drop_index("ix_audit_trail_fix_id", table_name="audit_trail")
    op.drop_index("ix_audit_trail_tenant_id", table_name="audit_trail")
    op.drop_table("audit_trail")

    op.drop_index("ix_suggested_fixes_issue_id", table_name="suggested_fixes")
    op.drop_index("ix_suggested_fixes_tenant_id", table_name="suggested_fixes")
    op.drop_table("suggested_fixes")

    op.drop_index("ix_issues_page_id", table_name="issues")
    op.drop_index("ix_issues_tenant_id", table_name="issues")
    op.drop_table("issues")

    op.drop_index("ix_page_metadata_page_id", table_name="page_metadata")
    op.drop_index("ix_page_metadata_tenant_id", table_name="page_metadata")
    op.drop_table("page_metadata")

    op.drop_index("ix_links_page_id", table_name="links")
    op.drop_index("ix_links_tenant_id", table_name="links")
    op.drop_table("links")

    op.drop_index("ix_pages_tenant_url", table_name="pages")
    op.drop_index("ix_pages_tenant_id", table_name="pages")
    op.drop_table("pages")
